image:
  repository: ghcr.io/rmortale/k8scc-web-client
  tag: 281a334

containerPort: 8080

vars:
  K8SCC_ENV: PROD

ingress:
  host: prod-k8scc.internal


resources:
  limits:
    cpu: "500m"
    memory: "1000Mi"
  requests:
    cpu: "200m"
    memory: "500Mi"

      

