image:
  repository: ghcr.io/rmortale/git-testing
  tag: 281a334

containerPort: 8080

vars:
  K8SCC_ENV: PROD

ingress:
  host: prod.internal


resources:
  limits:
    cpu: "500m"
    memory: "1000Mi"
  requests:
    cpu: "200m"
    memory: "500Mi"

      

