image:
  repository: ghcr.io/rmortale/k8scc-web-client
  tag: c910602

containerPort: 8080

vars:
  K8SCC_ENV: ACPT

ingress:
  host: acpt-k8scc.internal


resources:
  limits:
    cpu: "500m"
    memory: "1000Mi"
  requests:
    cpu: "200m"
    memory: "500Mi"

      

