image:
  repository: ghcr.io/rmortale/git-testing
  tag: sha-4d6a7d5

containerPort: 8080

vars:
  K8SCC_ENV: ACPT

ingress:
  host: acpt.internal


resources:
  limits:
    cpu: "500m"
    memory: "1000Mi"
  requests:
    cpu: "200m"
    memory: "500Mi"

      

